blog/urls.py
from django.urls import path
from .views import post_detail, post_list, post_search
from .feeds import LatestPostsFeed


app_name = 'blog'
urlpatterns = [
    # path('',PostListView.as_view() , name='post_list'),
    path('', post_list, name='post_list'),
    path('tag/<slug:tag_slug>', post_list, name='post_list_by_tag'),

    path('<int:year>/<int:month>/<int:day>/<slug:post>',
         post_detail,
         name='post_detail'),

    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', post_search, name='post_search'),
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

from blog.sitemaps import PostSiteMap
from blog.views import post_list

sitemaps = {
    'posts': PostSiteMap,
}

urlpatterns = [
    path('realadmin/docs/', include('django.contrib.admindocs.urls')),
    path('realadmin/', admin.site.urls),

    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {
         'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('', post_list, name='index')
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
from .manager import DraftManager, PublishManager


class Post(models.Model):
    """ This will store all the Post entries for our blog. You can check :model: `blog.Comment` 
    here
    """
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=150)
    slug = models.SlugField(unique_for_date='publish', max_length=250)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=50,
                              choices=STATUS_CHOICES,
                              default='draft')

    objects = models.Manager()
    published = PublishManager()
    draft = DraftManager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):

        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.month,
                                                 self.publish.day,
                                                 self.slug,
                                                 ])


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')

    name = models.CharField(max_length=50, help_text='Your name here.')
    email = models.EmailField(blank=True, null=True,
                              help_text="Enter your Email Here!")

    body = models.TextField(help_text='Your comment here')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True,)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f"comment by '{self.name}' on '{self.post}'"

blog/forms.py
from django import forms
from .models import Comment


class SearchForm(forms.Form):
    query = forms.CharField(max_length=30, )


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.EmailField()
    to = forms.EmailField()
    comment = forms.CharField(widget=forms.Textarea, required=False)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("name", 'email', 'body')
        widgets = {'name': forms.TextInput(
            attrs={'placeholder': "Enter you name here"}),
            'email': forms.TextInput(attrs={'placeholder': 'Enter your email here.'}),
            'body': forms.Textarea(attrs={"placeholder": "Enter your feedback  here"})

        }

blog/views.py
from django.contrib.postgres.search import (SearchQuery, SearchRank,
                                            SearchVector)
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db import connections
from django.db.models import Q
from django.http import request
from django.shortcuts import get_object_or_404, render
from taggit.models import Tag

from .forms import CommentForm, EmailPostForm, SearchForm
from .models import Post


def post_list(request, tag_slug=None):
    """ This will List all the Post in our
    **Template:**

    :template:`blog/post/list.html`
    """
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug, )
        object_list = object_list.filter(tags_in=[tag])

    paginator = Paginator(object_list, 3)  # this will show 3 post/page
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, "blog/post/list.html", {
        'page': page,
        'posts': posts,
        'tag': tag
    })


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day,
                             )

    # list of active comment for this post
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()

    comment_form = CommentForm()
    context = {'post': post,
               'comments': comments,
               'new_comment': new_comment,
               'comment_form': comment_form}
    return render(request, 'blog/post/detail.html', context)


def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            if connections['default'].vendor == 'sqlite':
                # very basics search functionality
                results = Post.published.filter(
                    Q(title__icontains=query) | Q(body__icontains=query)
                )
            if connections['default'].vendor == 'postgresql':
                # builtin search method of postgresSql
                search_vector = SearchVector('title', 'body')
                search_query = SearchQuery(query)
                results = Post.published.annotate(
                    search=search_vector,
                    rank=SearchRank(search_vector, search_query)
                ).filter(search=search_query).order_by('-rank')
    ctx = {
        'form': form,
        'query': query,
        'results': results
    }
    return render(request, 'blog/post/search.html', context=ctx)

blog/templates/blog/base.html
{% load static %}
{% load blog_tags %}
{% load crispy_forms_tags %}
<html lang="en">

<head>
    {% block stylesheets %}
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'blog.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% endblock stylesheets %}
    <title>{% block title %}{% endblock title %}</title>

</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'index' %}">My Blog</a>
        <button class="navbar-toggler d-lg-none" type="button"></button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'blog:post_list' %}">Home </a>
                </li>
            </ul>
    </nav>
    <div class="container " id="">
        {% block content %}
        {% endblock %}

    </div>
    <div id="sidebar" class="">
        <h2>My blog</h2>
        <p> <a class="btn btn-outline-info" href="{% url 'blog:post_feed' %}">
                Subscribe to RSS</a> </p>
        <p>This is my blog. I've written {% total_posts %} posts so far.</p>
        <h3>Latest Posts</h3>
        {%  show_latest_posts 2 %}
        <h3>Most Commented Posts</h3>
        {% get_most_commented_posts as most_commented_posts %}


        {% for post in most_commented_posts %}
        <ul>
            <li>
                <a href="{{ post.get_absolute_url }}">{{post.title}}</a>
            </li>
        </ul>
        {% endfor %}

    </div>
</body>

</html>

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% load crispy_forms_tags %}



{% block title %}
{{post.title}}
{% endblock title %}



{% block content %}
<h1> {{post.title}}</h1>

<p class="text text-muted small">Published by {{post.publish}} by author {{post.author}} </p>

{{ post.body|markdown }}



{% with comments.count as total_comments %}
<h4> {{ total_comments }} Comment{{total_comments|pluralize}}</h4>

{% endwith %}


{% for comment in comments %}
<div class="comment">
    <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name}}

    </p>
    {{comment.body|linebreaks}}


</div>
{% empty %}
<p class="text-muted small">There are no comments yet.</p>
{% endfor %}



{% if new_comment %}
<h2>Your comment has been added!</h2>
{% else %}
<h4>Add a new comment here.</h4>
<form method="post">
    {% csrf_token %}
    {{ comment_form|crispy}}
    <input class="btn form-control btn-success" type="submit" value="Add new comment">
</form>
{% endif %}


{% endblock content %}

blog/templates/blog/post/latest_posts.html
<ul>

    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title}}</a>
    </li>
    {% endfor %}

</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}
{% block content %}
    <h1>My Blog</h1> <hr />
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}"> {{ post.title }}</a>
        </h2>
        {% if tag %}
            <p class="muted">Tags: {{post.tags.all|join:", "}}</p>
        {% endif %}
        <p class="small text-muted">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords_html:5 }}
    {% endfor %}


    {% include 'pagination.html' with page=posts %}
{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% block title %}Search{% endblock %}

{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
        {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
        {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
            {{ post.body|truncatewords:5 }}
        {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}
            <p><a href="{% url 'blog:post_search' %}">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form action="." method="get">
        {{ form.as_p }}
        <input type="submit" class="btn btn-sm btn-outline-info"  value="Search">
        </form>
    {% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>